### ISSUE TITLE
Set BASE_URL in provider config

### ISSUE THREAD

**Issue by encima** [severalnines/terraform-provider-ccx#12]
When configuring the provider, client ID and secret are provided. Endpoint (or BASE_URL) needs to be provided (can default the public CCX)

This would be set [here](https://github.com/severalnines/terraform-provider-ccx/blob/05ec5efc8b42bb99757a7b912b8ccc3d4d7f6a1d/provider/provider.go#L28)

**Comment by freddielunchbird** [comment]
fixed and released
