### ISSUE TITLE
Do not ignore errors

### ISSUE THREAD

**Issue by skamenetskiy** [severalnines/terraform-provider-ccx#6]
https://github.com/severalnines/terraform-provider-ccx/blob/de9dedf9eb234fa3375b0476549abbc906038161/services/ccx_deployment_service.go#L155
https://github.com/severalnines/terraform-provider-ccx/blob/de9dedf9eb234fa3375b0476549abbc906038161/services/ccx_deployment_service.go#L167

Never ever ignore the error 😄

**Comment by freddielunchbird** [comment]
fixed and released
